name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.CPANEL_HOST }}
        user: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }} 
        remoteDir: "github_workflow"
        options: "--asci"