name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in GitHub workspace
        run: ls -al ${{ github.workspace }}

      - name: FTP Deployment
        uses: samueldelesque/ftp-action@v1.1.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          dir: /public_html/
          args: --ftp-create-dir --ftp-verbose