name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install openssh-client -y

    - name: Start SSH Agent and Add Key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_CPANEL_KEY }}"   # Use '<<<' to feed passphrase from secret

    - name: Sync files to cPanel
      run: |
        rsync -avz --delete-after ./ hajiiuzu@hajians.co:/home/hajiiuzu/trust-pos -e 'ssh -p 21098'

    - name: Stop SSH Agent
      run: |
        ssh-agent -k
